on: [push]

name: CI

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    name: Rust project
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Install system deps
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get install gcc-c++ remmina libX11-devel libxkbcommon-x11-devel

      - run: | 
          cd src/worker/rust-backend
          cargo build --release --all-features

