on: [push]

name: CI

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: Rust project
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      
      - name: Install system deps
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get install g++ pkg-config libx11-dev libxi-dev libxtst-dev libasound2-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb-composite0-dev

      - run: | 
          cd src/worker/rust-backend
          cargo build --release --all-features

